groups:
- name: ./rules.conf
  rules:

  # heartbeat alert
  - alert: Heartbeat
    expr: vector(1)
    labels:
      severity: informational

  - alert: OutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighCpuLoad
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: ResponseTimeAlert
    expr: rate(django_http_requests_latency_including_middlewares_seconds_bucket{le="0.1"}[1m]) > 0.4
    for: 1m
    annotations:
      summary: "A few fast requests came!"
      description: "{{ $labels.instance }} has a few fast requests!"
